const std = @import("std");

const o = true;
const x = false;

pub fn getGliderGunPattern() [34][46]bool {
    return [34][46]bool{
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, o, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x },
        .{ x, o, o, x, x, x, x, x, x, x, x, o, x, x, x, x, x, o, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, o, o, x, x, x, x, x, x, x, x, o, x, x, x, o, x, o, o, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, o, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
    };
}

pub fn getSpaceShipsPattern() [34][46]bool {
    return [34][46]bool{
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, o, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, o, o, o, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, o, o, o, o, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, o, o, x, x, o, o, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, o, x, o, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, o, x, x, x, x },
        .{ x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, o, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, o, o, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, o, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
    };
}

pub fn getClocksPattern() [34][46]bool {
    return [34][46]bool{
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, o, o, o, x, x, o, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x },
        .{ x, o, o, x, o, x, x, x, x, o, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, o, o, x, o, o, x, x, x, o, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, o, x, o, x, o, o, x, x, x, o, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, o, x, x, o, x, o, o, x, x, o, o, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, o, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, o, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, o, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, o, x, x, x },
        .{ x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, o, x },
        .{ x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, o, x },
        .{ x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, o, o, x, x, x },
        .{ x, x, o, o, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x, o, o, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, o, x, x, x, x, x, o, o, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
    };
}

pub fn getAbout() [34][46]bool {
    return [34][46]bool{
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, o, x, x, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, o, o, x, x, x, o, x, x, x, x, x, x, x, x, x, x, o, o, x, x, o, o, x, o, o, x, o, x, o, o, o, x, o, x, o, o, o, x, o, o, x, o, o, o },
        .{ x, x, o, x, o, x, x, x, o, x, x, x, x, x, x, x, x, x, o, x, o, x, o, x, x, o, x, x, o, x, o, x, o, x, o, x, x, o, x, x, o, x, x, o, x, o },
        .{ x, x, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x, x, o, x, o, x, o, x, x, o, x, x, o, x, o, x, o, x, o, x, x, o, x, x, o, x, x, o, x, o },
        .{ x, x, x, o, x, x, o, o, o, o, x, x, x, x, x, x, x, x, o, o, o, x, o, x, x, o, x, x, o, x, o, o, x, x, o, x, x, o, x, x, o, o, x, o, o, x },
        .{ x, x, o, x, x, x, x, o, o, o, x, x, x, x, x, x, x, x, o, x, o, x, o, x, x, o, x, x, o, x, o, x, x, x, o, x, x, o, x, x, o, x, x, o, x, o },
        .{ x, x, x, o, x, x, x, x, o, o, o, x, x, x, x, x, x, x, o, x, o, x, x, o, x, x, o, x, o, x, o, x, x, x, o, x, x, o, x, x, o, o, x, o, x, o },
        .{ x, x, o, x, x, x, o, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, o, x, x, x, o, x, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, o, x, x, o, o, x, o, x, x, x, x, x, x, x, o, o, x, x, o, o, x, x, o, x, o, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, o, o, o, o, x, x, x, x, x, o, x, o, o, o, x, x, x, o, x, o, x, o, x, o, x, o, x, o, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ o, o, o, x, x, o, x, x, x, x, x, o, x, o, o, o, x, x, o, x, o, x, o, x, o, x, o, x, o, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ o, o, o, o, x, x, o, x, x, o, o, o, o, x, o, o, x, x, o, x, o, x, o, x, o, x, o, x, o, x, o, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, o, o, o, o, x, x, o, o, x, x, o, o, x, x, o, x, x, o, x, o, x, o, x, o, x, o, o, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, o, o, o, o, x, x, x, o, x, x, o, x, x, x, x, x, o, x, o, x, x, o, o, x, o, x, x, x, o, x, o, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, o, o, o, o, o, x, x, o, o, x, x, o, o, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
        .{ x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x },
    };
}
